version: '3.8'

services:
  backend:
    build:
      context: ./browsestore
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db
    container_name: backend
    networks:
      - app-network

  frontend:
    build:
      context: ./tathy-festa-web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8082
    networks:
      - app-network

  db:
    image: postgres
    container_name: 8bdcd2186b74
    hostname: 8bdcd2186b74
    mac_address: "02:42:ac:11:00:02"
    environment:
      - LANG=en_US.utf8
      - PG_MAJOR=16
      - PG_VERSION=16.1-1.pgdg120+1
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=admin
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/16/bin
      - GOSU_VERSION=1.16
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: no
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
