version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: browsestore
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
