version: '3.8'

services:
  backend:
    build:
      context: ./browsestore
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - db

  frontend:
    build:
      context: ./tathy-festa-web-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"